#!/bin/bash
# SessionStart hook — prepare a Claude Code cloud session to run the gates.
#
# Cloud sessions clone the repo into a fresh container with no node_modules,
# so Vitest (Ring 4) and oxlint cannot run until deps are installed. Local
# checkouts already have theirs, so this is a no-op off-cloud.
#
# The npm project lives in frontend/, not the repo root — there is no root
# package.json. Backend (Ring 0/1, Python) deps are NOT installed here:
# `pip install -e ".[dev]"` pulls numpy/pandas/scipy/anthropic and would add
# minutes to every session start. Run it by hand from backend/ when you need
# the Python suite.
#
# Never fail the session: every path exits 0.

if [ "$CLAUDE_CODE_REMOTE" != "true" ]; then
  exit 0
fi

cd "${CLAUDE_PROJECT_DIR:-.}/frontend" || exit 0

npm ci --no-fund --no-audit || npm install --no-fund --no-audit

# npm optional-deps bug (npm/cli#4828): rolldown's platform binding can be
# skipped, which breaks Vitest. Same guard as .github/workflows/ci.yml.
node -e "require('rolldown')" 2>/dev/null \
  || npm install --no-save --force @rolldown/binding-linux-x64-gnu

# Bridge the env-var naming gap.
#
# vite.config.js REFUSES to build without VITE_SUPABASE_URL and
# VITE_SUPABASE_PUBLISHABLE_KEY (Ring 5 / G5.1 — a build without them emits a
# bundle with the whole app dead-code-eliminated). Vite only exposes
# VITE_-prefixed names, so a variable under any other prefix is invisible to it.
#
# The Race Engineer - Dev cloud environment supplies the correct values for the
# right project under Next.js names (NEXT_PUBLIC_SUPABASE_URL /
# NEXT_PUBLIC_SUPABASE_ANON_KEY), so `npm run build` and `npm run dev` fail out
# of the box. Map them into .env.local, which Vite's loadEnv reads and
# .gitignore already excludes via `*.local`. The values are publishable by
# design (RLS is the security boundary), not secrets.
#
# Prefer real VITE_* vars when present, and never clobber an existing file.
if [ ! -f .env.local ]; then
  url="${VITE_SUPABASE_URL:-${NEXT_PUBLIC_SUPABASE_URL:-}}"
  key="${VITE_SUPABASE_PUBLISHABLE_KEY:-${NEXT_PUBLIC_SUPABASE_ANON_KEY:-}}"
  if [ -n "$url" ] && [ -n "$key" ]; then
    {
      echo "# Generated by scripts/cloud_setup.sh from the cloud environment's"
      echo "# NEXT_PUBLIC_SUPABASE_* variables. Delete to regenerate."
      echo "VITE_SUPABASE_URL=$url"
      echo "VITE_SUPABASE_PUBLISHABLE_KEY=$key"
    } > .env.local
  fi
fi

exit 0
