// Ring 1 (G1.1–G1.5) + Ring 4 (G4.1–G4.2) — JS parsers vs the committed
// golden masters. The golden masters were generated by the verified Python
// reference implementation from exactly the committed fixture bytes
// (hashes in fixtures/FIXTURE_NOTES.md — G4.3). This suite is the pilot's
// enforcement of TESTING_GATES.md §5: the JS port must reproduce the
// verified decode value-for-value (float tolerance only).
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { parseLd, decodeSamples, decodeAll, lapBoundaries } from './ld.js';
import { parseLdx, setupSummary } from './ldx.js';
import { parseSvm, vehicleInfo, energyScheme } from './svm.js';
import { domainOf } from './domain.js';

const FIXTURES = join(dirname(fileURLToPath(import.meta.url)), '../../../../fixtures');

const ldBytes = new Uint8Array(readFileSync(join(FIXTURES, 'cota_gte_sanitized.ld')));
const ldxText = readFileSync(join(FIXTURES, 'cota_gte_sanitized.ldx'), 'utf-8');
const svmText = readFileSync(join(FIXTURES, 'cota_gte_sanitized.svm'), 'utf-8');
const goldenLd = JSON.parse(readFileSync(join(FIXTURES, 'golden_master_ld.json'), 'utf-8'));
const goldenLdx = JSON.parse(readFileSync(join(FIXTURES, 'golden_master_ldx.json'), 'utf-8'));
const goldenSvm = JSON.parse(readFileSync(join(FIXTURES, 'golden_master_svm.json'), 'utf-8'));
const goldenDomains = JSON.parse(
  readFileSync(join(FIXTURES, 'golden_master_domains.json'), 'utf-8'),
);

// Golden decoded values are rounded to 4 decimals by the generator; allow
// only that rounding margin. "Float tolerance only" per G4.1.
const TOL = 5.0000001e-5;

describe('G4.1 / G1.2 — .ld decode matches the golden master', () => {
  const ld = parseLd(ldBytes);
  decodeAll(ldBytes, ld);

  it('header matches', () => {
    expect(ld.header).toEqual(goldenLd.header);
  });

  it('G0.2 — driver field is the scrub placeholder', () => {
    expect(ld.header.driver).toBe('DRIVER_REDACTED');
  });

  it('discovers exactly the golden channel set', () => {
    expect(Object.keys(ld.channels).sort()).toEqual(
      Object.keys(goldenLd.channels).sort(),
    );
    expect(Object.keys(ld.channels).length).toBe(goldenLd.channel_count);
  });

  it('per-channel decode metadata matches (mul/dec/shift/scale/rate/unit/size)', () => {
    for (const [name, g] of Object.entries(goldenLd.channels)) {
      const ch = ld.channels[name];
      expect(ch, name).toBeDefined();
      expect(ch.mul, `${name}.mul`).toBe(g.mul);
      expect(ch.dec, `${name}.dec`).toBe(g.dec);
      expect(ch.shift, `${name}.shift`).toBe(g.shift);
      expect(ch.scale, `${name}.scale`).toBe(g.scale);
      expect(ch.sampleRateHz, `${name}.rate`).toBe(g.sample_rate_hz);
      expect(ch.sampleCount, `${name}.count`).toBe(g.sample_count);
      expect(ch.bytesPerSample, `${name}.size`).toBe(g.bytes_per_sample);
      expect(ch.unit, `${name}.unit`).toBe(g.unit);
    }
  });

  it('decoded traces match value-for-value within rounding tolerance', () => {
    for (const [name, g] of Object.entries(goldenLd.channels)) {
      const ch = ld.channels[name];
      expect(ch.samples.length, `${name} sample count`).toBe(g.decoded.length);
      for (let i = 0; i < g.decoded.length; i++) {
        const diff = Math.abs(ch.samples[i] - g.decoded[i]);
        if (diff > TOL) {
          throw new Error(`${name}[${i}] diverges: js=${ch.samples[i]} golden=${g.decoded[i]}`);
        }
      }
      const min = Math.min(...ch.samples);
      const max = Math.max(...ch.samples);
      expect(Math.abs(min - g.decoded_min), `${name}.min`).toBeLessThanOrEqual(TOL);
      expect(Math.abs(max - g.decoded_max), `${name}.max`).toBeLessThanOrEqual(TOL);
    }
  });

  it('G1.3 — quality flags match the golden master (reliable / all_zero)', () => {
    for (const [name, g] of Object.entries(goldenLd.channels)) {
      const ch = ld.channels[name];
      expect(ch.reliable, `${name}.reliable`).toBe(g.reliable);
      expect(ch.allZero, `${name}.all_zero`).toBe(g.all_zero);
    }
  });

  it('G1.3 — lap boundaries come from the .ld Lap Number channel', () => {
    const bounds = lapBoundaries(ld).map(({ lap, startS }) => ({ lap, start_s: startS }));
    expect(bounds).toEqual(goldenLd.lap_boundaries);
  });
});

describe('G1.5 — decode assumptions pinned to real-byte evidence', () => {
  const ld = parseLd(ldBytes);

  it('scale is 1 for 67/70 channels; 50/50/9 for the three exceptions', () => {
    expect(ld.channels['Ambient Temperature'].scale).toBe(50);
    expect(ld.channels['Track Temperature'].scale).toBe(50);
    expect(ld.channels['Steering Wheel Position'].scale).toBe(9);
    const nonOne = Object.values(ld.channels).filter((c) => c.scale !== 1);
    expect(nonOne.map((c) => c.name).sort()).toEqual([
      'Ambient Temperature', 'Steering Wheel Position', 'Track Temperature',
    ]);
  });

  it('temperature channels decode to plausible values (the scale=50 fix)', () => {
    const amb = decodeSamples(ldBytes, ld.channels['Ambient Temperature']);
    expect(Math.max(...amb)).toBeGreaterThan(20);
    expect(Math.max(...amb)).toBeLessThan(45);
  });

  it('no float32 channels — the only 4-byte channels are the int32 GPS pair', () => {
    const fourByte = Object.values(ld.channels).filter((c) => c.bytesPerSample === 4);
    expect(fourByte.map((c) => c.name).sort()).toEqual(['GPS Latitude', 'GPS Longitude']);
    const lon = decodeSamples(ldBytes, ld.channels['GPS Longitude']);
    // int32 gives game-world coords; float32 misreads give ±1e38 garbage
    expect(Math.min(...lon)).toBeGreaterThan(-136);
    expect(Math.min(...lon)).toBeLessThan(-134);
  });

  it('G1.4 — truncated input decodes without crashing and without overread', () => {
    const cut = ldBytes.slice(0, Math.floor(ldBytes.length * 0.6));
    const ld2 = parseLd(cut);
    for (const ch of Object.values(ld2.channels)) {
      const out = decodeSamples(cut, ch); // must not throw
      expect(out.length).toBeLessThanOrEqual(ch.sampleCount);
    }
  });
});

describe('G4.1 — .ldx parse matches the golden master', () => {
  const ldx = parseLdx(ldxText);

  it('session summary matches', () => {
    expect(ldx.totalLaps).toBe(goldenLdx.total_laps);
    expect(ldx.fastestLap).toBe(goldenLdx.fastest_lap);
    expect(ldx.fastestTimeRaw).toBe(goldenLdx.fastest_time_raw);
    expect(Math.abs(ldx.fastestTimeS - goldenLdx.fastest_time_s)).toBeLessThan(1e-9);
  });

  it('setup block: full param count and truncation detector', () => {
    expect(Object.keys(ldx.setup).length).toBe(goldenLdx.setup_param_count);
    // the known MoTeC export bug: BrakePressure is truncated in the .ldx
    expect(ldx.setup.BrakePressure.truncated).toBe(true);
  });

  it('setup summary matches key-for-key', () => {
    expect(setupSummary(ldx)).toEqual(goldenLdx.setup_summary);
  });
});

describe('G4.1 — .svm parse matches the golden master', () => {
  const svm = parseSvm(svmText);

  it('sections match exactly (idx + //comment values)', () => {
    expect(svm.sections).toEqual(goldenSvm.sections);
    expect(svm.sectionCount).toBe(goldenSvm.section_count);
  });

  it('vehicle info splits the class string', () => {
    expect(vehicleInfo(svm)).toEqual({
      car: 'Ferrari_488_GTE_EVO', carClass: 'GTE', ruleset: 'WEC2023',
    });
  });

  it('energy branch: GTE carries fuel, not virtual energy', () => {
    expect(energyScheme(svm)).toBe('fuel');
    // the untruncated value the .ldx cut off lives here (setup source priority)
    expect(svm.sections.CONTROLS.BrakePressureSetting.value).toBe('68 kgf  (85%)');
  });
});

describe('G4.2 — domain classification matches the committed snapshot', () => {
  it('all 70 channel names map to their frozen domains', () => {
    const ld = parseLd(ldBytes);
    const mapping = Object.fromEntries(
      Object.keys(ld.channels).map((n) => [n, domainOf(n)]),
    );
    expect(mapping).toEqual(goldenDomains.domains);
  });
});
