// Ring 1 (G1.1–G1.5) + Ring 4 (G4.1–G4.2) — JS parsers vs the committed
// golden masters. The golden masters were generated by the verified Python
// reference implementation from exactly the committed fixture bytes
// (hashes in fixtures/FIXTURE_NOTES.md — G4.3). This suite is the pilot's
// enforcement of TESTING_GATES.md §5: the JS port must reproduce the
// verified decode value-for-value (float tolerance only).
import { describe, it, expect } from 'vitest';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { parseLd, decodeSamples, decodeAll, lapBoundaries } from './ld.js';
import { parseLdx, setupSummary } from './ldx.js';
import { parseSvm, vehicleInfo, energyScheme } from './svm.js';
import { domainOf } from './domain.js';

const FIXTURES = join(dirname(fileURLToPath(import.meta.url)), '../../../../fixtures');

const ldBytes = new Uint8Array(readFileSync(join(FIXTURES, 'cota_gte_sanitized.ld')));
const ldxText = readFileSync(join(FIXTURES, 'cota_gte_sanitized.ldx'), 'utf-8');
const svmText = readFileSync(join(FIXTURES, 'cota_gte_sanitized.svm'), 'utf-8');
const goldenLd = JSON.parse(readFileSync(join(FIXTURES, 'golden_master_ld.json'), 'utf-8'));
const goldenLdx = JSON.parse(readFileSync(join(FIXTURES, 'golden_master_ldx.json'), 'utf-8'));
const goldenSvm = JSON.parse(readFileSync(join(FIXTURES, 'golden_master_svm.json'), 'utf-8'));
const goldenDomains = JSON.parse(
  readFileSync(join(FIXTURES, 'golden_master_domains.json'), 'utf-8'),
);

// Golden master v2 (21 Aug 2026) asserts each channel with a SHA-256 over its
// COMPLETE decoded array rather than embedding every value — the multi-lap
// fixture carries 412,850 decoded values, which as full arrays was ~6 MB of
// committed JSON. The hash covers every sample; decimating would not.
//
// The canonical form must match backend/scripts/generate_golden_masters.py
// byte for byte or nothing verifies: 6 fixed decimals, negative zero
// normalised (Python renders -0.0 as "-0.000000", JS's toFixed gives
// "0.000000"), joined by ',', hashed as UTF-8.
const DECIMALS = 6;
function canonical(values) {
  const parts = new Array(values.length);
  for (let i = 0; i < values.length; i++) {
    const v = values[i] === 0 ? 0 : values[i];
    parts[i] = v.toFixed(DECIMALS);
  }
  return parts.join(',');
}
function digest(values) {
  return createHash('sha256').update(canonical(values), 'utf8').digest('hex');
}
// Single-pass extremes: the fixture's fastest channels hold 29,490 samples, and
// Math.min(...arr) is exactly the spread that throws RangeError on long arrays.
function extremes(values) {
  let min = Infinity;
  let max = -Infinity;
  for (const v of values) {
    if (v < min) min = v;
    if (v > max) max = v;
  }
  return { min, max };
}
const round6 = (v) => Number(v.toFixed(DECIMALS));

describe('G4.1 / G1.2 — .ld decode matches the golden master', () => {
  const ld = parseLd(ldBytes);
  decodeAll(ldBytes, ld);

  it('header matches', () => {
    expect(ld.header).toEqual(goldenLd.header);
  });

  it('G0.2 — driver field is the scrub placeholder', () => {
    expect(ld.header.driver).toBe('DRIVER_REDACTED');
  });

  it('discovers exactly the golden channel set', () => {
    expect(Object.keys(ld.channels).sort()).toEqual(
      Object.keys(goldenLd.channels).sort(),
    );
    expect(Object.keys(ld.channels).length).toBe(goldenLd.channel_count);
  });

  it('per-channel decode metadata matches (mul/dec/shift/scale/rate/unit/size)', () => {
    for (const [name, g] of Object.entries(goldenLd.channels)) {
      const ch = ld.channels[name];
      expect(ch, name).toBeDefined();
      expect(ch.mul, `${name}.mul`).toBe(g.mul);
      expect(ch.dec, `${name}.dec`).toBe(g.dec);
      expect(ch.shift, `${name}.shift`).toBe(g.shift);
      expect(ch.scale, `${name}.scale`).toBe(g.scale);
      expect(ch.sampleRateHz, `${name}.rate`).toBe(g.sample_rate_hz);
      expect(ch.sampleCount, `${name}.count`).toBe(g.count);
      expect(ch.bytesPerSample, `${name}.size`).toBe(g.bytes_per_sample);
      expect(ch.unit, `${name}.unit`).toBe(g.unit);
    }
  });

  it('every decoded sample matches the Python reference, by hash', () => {
    // 70 channels, 412,850 values. A hash mismatch means the JS port diverged
    // from the verified Python decode somewhere in that channel — the count,
    // extremes and edge assertions below narrow down where.
    for (const [name, g] of Object.entries(goldenLd.channels)) {
      const ch = ld.channels[name];
      expect(ch.samples.length, `${name} sample count`).toBe(g.count);
      expect(digest(ch.samples), `${name} decoded-array sha256`).toBe(g.sha256);
    }
  });

  it('decoded extremes and edge samples match, so a mismatch is diagnosable', () => {
    // Redundant with the hash when everything passes — and the only readable
    // signal when it does not.
    for (const [name, g] of Object.entries(goldenLd.channels)) {
      const ch = ld.channels[name];
      if (ch.samples.length === 0) continue;
      const { min, max } = extremes(ch.samples);
      expect(round6(min), `${name}.min`).toBe(g.min);
      expect(round6(max), `${name}.max`).toBe(g.max);
      expect(ch.samples.slice(0, g.first.length).map(round6), `${name}.first`).toEqual(g.first);
      expect(ch.samples.slice(-g.last.length).map(round6), `${name}.last`).toEqual(g.last);
    }
  });

  it('covers the whole fixture, not a truncated slice of it', () => {
    // The previous fixture had every channel record overwritten to report 300
    // samples, so it could not express multi-lap logic at all — and it hid two
    // real bugs. This pins that the committed fixture is the full session.
    const total = Object.values(goldenLd.channels).reduce((a, c) => a + c.count, 0);
    expect(total).toBe(goldenLd._meta.total_decoded_values);
    expect(total).toBeGreaterThan(400000);
  });

  it('G1.3 — quality flags match the golden master (reliable / all_zero)', () => {
    for (const [name, g] of Object.entries(goldenLd.channels)) {
      const ch = ld.channels[name];
      expect(ch.reliable, `${name}.reliable`).toBe(g.reliable);
      expect(ch.allZero, `${name}.all_zero`).toBe(g.all_zero);
    }
  });

  it('G1.3 — lap boundaries come from the .ld Lap Number channel', () => {
    const bounds = lapBoundaries(ld).map(({ lap, startS }) => ({
      lap,
      start_s: Number(startS.toFixed(3)),
    }));
    expect(bounds).toEqual(goldenLd.lap_boundaries);
    // The fixture must keep exercising multi-lap segmentation: an out-lap, at
    // least two timed laps, and a trailing partial.
    expect(bounds.length).toBeGreaterThanOrEqual(4);
  });
});

describe('G1.5 — decode assumptions pinned to real-byte evidence', () => {
  const ld = parseLd(ldBytes);

  it('scale is 1 for 67/70 channels; 50/50/9 for the three exceptions', () => {
    expect(ld.channels['Ambient Temperature'].scale).toBe(50);
    expect(ld.channels['Track Temperature'].scale).toBe(50);
    expect(ld.channels['Steering Wheel Position'].scale).toBe(9);
    const nonOne = Object.values(ld.channels).filter((c) => c.scale !== 1);
    expect(nonOne.map((c) => c.name).sort()).toEqual([
      'Ambient Temperature', 'Steering Wheel Position', 'Track Temperature',
    ]);
  });

  it('temperature channels decode to plausible values (the scale=50 fix)', () => {
    const amb = decodeSamples(ldBytes, ld.channels['Ambient Temperature']);
    expect(Math.max(...amb)).toBeGreaterThan(20);
    expect(Math.max(...amb)).toBeLessThan(45);
  });

  it('no float32 channels — the only 4-byte channels are the int32 GPS pair', () => {
    const fourByte = Object.values(ld.channels).filter((c) => c.bytesPerSample === 4);
    expect(fourByte.map((c) => c.name).sort()).toEqual(['GPS Latitude', 'GPS Longitude']);
    const lon = decodeSamples(ldBytes, ld.channels['GPS Longitude']);
    // int32 gives game-world coords; float32 misreads give ±1e38 garbage
    expect(Math.min(...lon)).toBeGreaterThan(-136);
    expect(Math.min(...lon)).toBeLessThan(-134);
  });

  it('G1.4 — truncated input decodes without crashing and without overread', () => {
    const cut = ldBytes.slice(0, Math.floor(ldBytes.length * 0.6));
    const ld2 = parseLd(cut);
    for (const ch of Object.values(ld2.channels)) {
      const out = decodeSamples(cut, ch); // must not throw
      expect(out.length).toBeLessThanOrEqual(ch.sampleCount);
    }
  });
});

describe('G4.1 — .ldx parse matches the golden master', () => {
  const ldx = parseLdx(ldxText);

  it('session summary matches', () => {
    expect(ldx.totalLaps).toBe(goldenLdx.total_laps);
    expect(ldx.fastestLap).toBe(goldenLdx.fastest_lap);
    expect(ldx.fastestTimeRaw).toBe(goldenLdx.fastest_time_raw);
    expect(Math.abs(ldx.fastestTimeS - goldenLdx.fastest_time_s)).toBeLessThan(1e-9);
  });

  it('setup block: full param count and truncation detector', () => {
    expect(Object.keys(ldx.setup).length).toBe(goldenLdx.setup_param_count);
    // the known MoTeC export bug: BrakePressure is truncated in the .ldx
    expect(ldx.setup.BrakePressure.truncated).toBe(true);
  });

  it('setup summary matches key-for-key', () => {
    expect(setupSummary(ldx)).toEqual(goldenLdx.setup_summary);
  });
});

describe('G4.1 — .svm parse matches the golden master', () => {
  const svm = parseSvm(svmText);

  it('sections match exactly (idx + //comment values)', () => {
    expect(svm.sections).toEqual(goldenSvm.sections);
    expect(svm.sectionCount).toBe(goldenSvm.section_count);
  });

  it('vehicle info splits the class string', () => {
    expect(vehicleInfo(svm)).toEqual({
      car: 'Ferrari_488_GTE_EVO', carClass: 'GTE', ruleset: 'WEC2023',
    });
  });

  it('energy branch: GTE carries fuel, not virtual energy', () => {
    expect(energyScheme(svm)).toBe('fuel');
    // the untruncated value the .ldx cut off lives here (setup source priority)
    expect(svm.sections.CONTROLS.BrakePressureSetting.value).toBe('68 kgf  (85%)');
  });
});

describe('G4.2 — domain classification matches the committed snapshot', () => {
  it('all 70 channel names map to their frozen domains', () => {
    const ld = parseLd(ldBytes);
    const mapping = Object.fromEntries(
      Object.keys(ld.channels).map((n) => [n, domainOf(n)]),
    );
    expect(mapping).toEqual(goldenDomains.domains);
  });
});
